### ISSUE TITLE
Unexpected character encountered while parsing value: R. Path '', line 0, position 0.

### ISSUE THREAD

**Issue by devfadl** [moyasar/moyasar-dotnet#17]
Hi there,

we  have an exception when use List function like below:

Unexpected character encountered while parsing value: R. Path '', line 0, position 0.
 at Newtonsoft.Json.JsonTextReader.ParseValue()     at Newtonsoft.Json.JsonTextReader.Read()     at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)     at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)     at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)     at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)     at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)     at Moyasar.Providers.JsonSerializer.Deserialize[TType](String json)     at Moyasar.MoyasarService.SendRequest(String httpMethod, String url, Dictionary`2 parameters)     at Moyasar.Services.Payment.List(SearchQuery query)    

assembly name : Newtonsoft.Json, Version=12.0.0.0, Culture=neutral 
AssemblyVersion : v4.0.30319 
ClassName :JsonTextReader
MethodName : ParseValue

**Comment by ecleel** [comment]
Hi Osama,

Does this issue happen each time you call list function? Also, Does this happen in payment list function or invoice list function?

**Comment by devfadl** [comment]
> Hi @devfadl,
> 
> Does this issue happen every time you call list function or it's happen in some calls? Also, Does this happen in payment list function or invoice list function?

when user List Function as below :
Payment.List(new Moyasar.Models.SearchQuery() { Page = page });
it happens each time

**Comment by fast4d** [comment]
@devfadl Please Update to the new version `2.0.3`, the new version now handles request throttling.

**Comment by shoa48** [comment]
Hello @devfadl 
Please note that Moyasar API now throttles the list action to up to 100 req/min for each account.
And you can use `created[gt]` and `created[lt]` as a search queries for a specific period of time instead of listing all the payments each time.

https://moyasar.com/docs/api/#query-parameters

**Comment by devfadl** [comment]
> @devfadl Please Update to the new version `2.0.3`, the new version now handles request throttling.

Thanks problem solved

**Comment by devfadl** [comment]
> Hello @devfadl
> Please note that Moyasar API now throttles the list action to up to 100 req/min for each account.
> And you can use `created[gt]` and `created[lt]` as a search queries for a specific period of time instead of listing all the payments each time.
> 
> https://moyasar.com/docs/api/#query-parameters

so is there another way to get payment by description value  ?

**Comment by fast4d** [comment]
Dear @devfadl, Searching by `description` is unfortunately not supported.

Please consider using [Ajax Form](https://moyasar.com/docs/payments/best-practices/using-ajax/) to save the payment id before letting the user proceed, this way you won't have to search for the payment if the redirection fails

**Comment by devfadl** [comment]
> Dear @devfadl, Searching by `description` is unfortunately not supported.
> 
> Please consider using [Ajax Form](https://moyasar.com/docs/payments/best-practices/using-ajax/) to save the payment id before letting the user proceed, this way you won't have to search for the payment if the redirection fails

Okay , Thanks i got it .
